import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [users, setUsers] = useState([]);

  const fetchUsers = useEffect(() => {
    const fetchData = async () => {
      const fetch_result = await fetch("http://localhost:5000/users");
      const result = await fetch_result.json();
      setUsers(result);
    };

    fetchData();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Lista de usuários</h1>
        <ul>
          <li class="header">
            <div>Nome</div>
            <div>E-mail</div>
            <div>Data de Cadastro</div>
          </li>
          {users?.length &&
            users.map((user, ix) => (
              <li key={ix}>
                <div>{user.name}</div>
                <div>{user.email}</div>
                <div>{user.created_at}</div>
              </li>
            ))}
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
